#pragma once

#include "Direction.h"
#include "../core/Vec2.h"

#include <cstdint>
#include <string>
#include <vector>

namespace neoncoil
{
    enum class Tile : std::uint8_t
    {
        Empty = 0,
        Wall = 1
    };

    // A sentinel patrols a straight, pre-validated corridor and reverses when it
    // is blocked. It is the main non-speed difficulty lever: it forces the
    // player to time routes rather than just react faster.
    struct Sentinel
    {
        Vec2 position{ 0, 0 };
        Vec2 step{ 1, 0 };
        float moveInterval{ 0.35f };
        float timer{ 0.0f };
    };

    // Static geometry plus the dynamic hazards that live on it. Generated by
    // LevelGenerator, which guarantees the invariants documented there.
    class Level
    {
    public:
        void resize(int width, int height);

        int width() const { return m_width; }
        int height() const { return m_height; }
        Vec2 size() const { return { m_width, m_height }; }

        bool inBounds(Vec2 position) const;

        // Out-of-bounds reads report Wall, so collision code never has to
        // bounds-check separately and can never index outside the grid.
        Tile at(Vec2 position) const;
        void set(Vec2 position, Tile tile);
        bool isWall(Vec2 position) const { return at(position) == Tile::Wall; }

        // True for the outermost ring, which nothing may ever pass through --
        // not even a phasing snake.
        bool isBorder(Vec2 position) const;

        // Turns a wall into floor (Bulwark's shield shatter). Refuses to open
        // the border. Returns whether anything changed.
        bool destroyWall(Vec2 position);

        const std::vector<Vec2>& openTiles() const { return m_openTiles; }
        void rebuildOpenTiles();

        void updateHazards(float deltaSeconds);
        bool hazardAt(Vec2 position) const;
        const std::vector<Sentinel>& sentinels() const { return m_sentinels; }
        void addSentinel(const Sentinel& sentinel) { m_sentinels.push_back(sentinel); }
        void clearSentinels() { m_sentinels.clear(); }

        Vec2 spawn{ 0, 0 };
        Direction spawnDirection{ Direction::Right };

        int index{ 1 };
        std::uint64_t seed{ 0 };
        std::wstring archetypeName{ L"Open" };

    private:
        int m_width{ 0 };
        int m_height{ 0 };
        std::vector<Tile> m_tiles;
        std::vector<Vec2> m_openTiles;
        std::vector<Sentinel> m_sentinels;
    };
}
